FROM python:3.11-slim

WORKDIR /app

RUN pip install uv

COPY pyproject.toml .
RUN uv pip install --system \
    httpx \
    pymongo \
    motor \
    pydantic \
    pydantic-settings \
    requests \
    fastapi

COPY src/ ./src/

CMD ["python", "-m", "src.service.batch.binance_historical_collector"]
