FROM python:3.11-slim

WORKDIR /app

RUN pip install uv

COPY pyproject.toml .
RUN uv pip install --system \
    pandas \
    numpy \
    scikit-learn \
    joblib

COPY src/ ./src/

CMD ["python", "src/service/predict/logistic_regression/train.py"]
