FROM python:3.11-slim

WORKDIR /app

RUN pip install uv

COPY pyproject.toml .
RUN uv pip install --system \
    pandas \
    numpy \
    scikit-learn \
    joblib \
    motor \
    pymongo \
    pydantic \
    pydantic-settings

COPY src/ ./src/

CMD ["python", "-m", "src.service.predict.logistic_regression.train"]
